// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpHLoqRA6KDc-TvawCzD9Px56WQnTEYW8',
    appId: '1:667935535397:web:a438fd70b2c0f8f25f6acc',
    messagingSenderId: '667935535397',
    projectId: 'isonow-ecdb2',
    authDomain: 'isonow-ecdb2.firebaseapp.com',
    storageBucket: 'isonow-ecdb2.firebasestorage.app',
    measurementId: 'G-H2RRC5JQ70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTEzvKMVmcnFefWW7qj2gikvwtNpgNMKo',
    appId: '1:667935535397:android:59947a246aae2d865f6acc',
    messagingSenderId: '667935535397',
    projectId: 'isonow-ecdb2',
    storageBucket: 'isonow-ecdb2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE0r9DIiL2ycORMA235-XSKaLQgfzdwyk',
    appId: '1:667935535397:ios:fb87ac7c5e5d04c55f6acc',
    messagingSenderId: '667935535397',
    projectId: 'isonow-ecdb2',
    storageBucket: 'isonow-ecdb2.firebasestorage.app',
    iosBundleId: 'com.example.isonow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE0r9DIiL2ycORMA235-XSKaLQgfzdwyk',
    appId: '1:667935535397:ios:fb87ac7c5e5d04c55f6acc',
    messagingSenderId: '667935535397',
    projectId: 'isonow-ecdb2',
    storageBucket: 'isonow-ecdb2.firebasestorage.app',
    iosBundleId: 'com.example.isonow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpHLoqRA6KDc-TvawCzD9Px56WQnTEYW8',
    appId: '1:667935535397:web:4ec30daab48e56d25f6acc',
    messagingSenderId: '667935535397',
    projectId: 'isonow-ecdb2',
    authDomain: 'isonow-ecdb2.firebaseapp.com',
    storageBucket: 'isonow-ecdb2.firebasestorage.app',
    measurementId: 'G-FY8R0CGH81',
  );
}
